# Generated by Django 4.2.5 on 2024-03-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormFillModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('job_role', models.CharField(choices=[('Back-end-developer', 'BACK_END_DEVELOPER'), ('Front-end-developer', 'FRONT_END_DEVELOPER'), ('ui/ux_developer', 'UI/UX-DEVELOPER'), ('python_developer', 'PYTHON_DEVELOPER'), ('django_develpoer', 'DJANGO-DEVELOPER')], default='Job', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, unique=True)),
                ('gender', models.CharField(choices=[('female', 'FEMALE'), ('male', 'MALE'), ('other', 'other')], default='', max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
            ],
        ),
    ]
